workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
