name: clean_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  cupertino_icons: ^1.0.8
  bcrypt: ^1.1.3
  flutter_secure_storage: ^9.0.0

  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/hall.png
    - assets/hotel.png
    - assets/bride_salon.png
    - assets/restaurant.png
    - assets/bride_dress.png
    - assets/salon_care.png
    - assets/groom_hamam.png
    - assets/groom_suit.png
    - assets/car.png
    - assets/car_decoration.png
    - assets/honeymoon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"
  adaptive_icon_background: "#2B0606" # لون ماروني غامق حسب طلبك

flutter_native_splash:
  image: assets/app_icon.png
  color: "#ffffff"
  android: true
  ios: true

